version: "3.9"

services:
  db:
    image: postgres:16
    container_name: recipe-db
    restart: always
    environment:
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_pass
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: recipe-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://recipe_user:recipe_pass@db:5432/recipe_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python -m app.db.seed && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pgdata: